### ISSUE TITLE
output-management: add make, model, serial

### ISSUE THREAD

**Issue by emersion** [swaywm/wlr-protocols#68]
These would be useful for utilities matching make/model/serial against a configuration file, to recognize a screen even if it doesn't use the same connector. These would be optional (not all backends support it) and not intended to be displayed to the user (see "description").

**Comment by subdiff** [comment]
#### Differentiating between different displays on same connector
This is also important to differentiate between displays connected to the same connector. I would even say this the more important use case since displays can have very different properties and config load/save should depend on these properties (think of resolution and scale).

#### Same display on different connectors 
On the other side a small but important detail for configuration file matching is that displays on different connectors might show different properties. For example for the same display a mode being available when connected via DP but not available via HDMI.

So either the output `name` (describes the connector) should still be additionally used for config save/load or at least the compatibility of a stored configuration must be checked on load. But the second solution is more complicated and might make additional problems with something like for example then a suddenly inappropriate stored scale value. I would just save output configurations according to make, model, serial plus name.
